### ISSUE TITLE
Subaru.fetch and Subaru.update - Description Mismatch

### ISSUE THREAD

**Issue by mpogue1996** [G-Two/homeassistant-subaru#40] opened 2022-01-09 01:47 UTC
If you check the services that run on the Lovelace UI buttons "Update" and "Poll Vehicle", and verify them against the services that they call (Subaru.update and Subaru.fetch), you'll notice that the descriptions for these services are actually swapped. 

The Subaru.fetch service does actually poll the vehicle.

**Comment by G-Two** [comment] 2022-01-09 18:39
I'm not sure I understand where the issue is. Is this with the newly implemented buttons in the prerelease? Please reference the specific file in the repo where you found the description mismatch.

**Comment by ACiDGRiM** [comment] 2022-01-10 21:28
I think mpogue1996 should move his automations to use the button press entities

However, it appears that the button.refresh only does the fetch (pulls latest data) and a button.update (asks the car for the latest data) does not exist.

**Comment by G-Two** [comment] 2022-01-11 03:39
I thought fetch and update were too similar sounding, so with the v0.6.0 buttons I named them refresh and locate. The old subaru.update service simply issued a remote locate command, which also resulted in new sensor data being sent by the vehicle with the location. 

In short:
* button.refresh == subaru.fetch 
  * Does not poll the vehicle, just gets the last state the vehicle sent, usually at engine shutdown
* button.locate == subaru.update 
  * Polls the vehicle for location update and new sensor data

subaru.fetch has never polled the vehicle, so if there's an error in the code or a description anywhere, I'd like to fix it.

**Comment by ACiDGRiM** [comment] 2022-01-19 06:29
Good to know that the locate button does the polling. I do think that seems a bit un-selfexplanitory, however I can't think of a better name other than button.poll. But my major issues are all solved, I can't reproduce any issues the original user reported.

**Comment by G-Two** [comment] 2024-01-21 16:45
Resolved with v0.7.0

**Closed by G-Two** 2024-01-21 16:45 UTC
